using BuildingBlocks.Domain;

namespace Expense.API.Domain.Entities;

/// <summary>
/// Represents a simplified debt between two users within a trip.
/// Generated by the debt simplification algorithm.
/// </summary>
public class DebtRecord : BaseEntity
{
    public Guid TripId { get; set; }
    public Guid FromUserId { get; set; }
    public Guid ToUserId { get; set; }
    public decimal Amount { get; set; }
    public string Currency { get; set; } = "VND";
    public bool IsSettled { get; set; }
    public DateTime? SettledAt { get; set; }
}
